# coding: utf-8
# Copyright (c) PJ Ren.
# Distributed under the terms of the MIT License.
'''
This module contain all the input parameters for pwscf. One can get the 
para list by following shell command. The input_parameters.f90 is in 
$qe_src/Modules/.
'''
NAMELIST = {}

NAMELIST['control'] = ('title', 'calculation', 'verbosity', 'restart_mode', 'nstep', 'iprint', 'isave', 'tstress', 'tprnfor', 'dt', 'ndr', 'ndw', 'outdir', 'prefix', 'wfcdir', 'max_seconds', 'ekin_conv_thr', 'etot_conv_thr', 'forc_conv_thr', 'pseudo_dir', 'disk_io', 'tefield', 'dipfield', 'lberry', 'gdir', 'nppstr', 'wf_collect', 'lelfield', 'nberrycyc', 'refg', 'tefield2', 'saverho', 'tabps', 'lkpoint_dir', 'use_wannier', 'lecrpa', 'tqmmm', 'vdw_table_name', 'lorbm', 'memory', 'point_label_type', 'lfcpopt', 'lfcpdyn', 'input_xml_schema_file', 'monopole')

NAMELIST['system'] = ('ibrav', 'celldm', 'a', 'b', 'c', 'cosab', 'cosac', 'cosbc', 'nat', 'ntyp', 'nbnd', 'ecutwfc', 'ecutrho', 'nr1', 'nr2', 'nr3', 'nr1s', 'nr2s', 'nr3s', 'nr1b', 'nr2b', 'nr3b', 'nosym', 'nosym_evc', 'noinv', 'use_all_frac', 'force_symmorphic', 'starting_magnetization', 'occupations', 'degauss', 'nspin', 'ecfixed', 'qcutz', 'q2sigma', 'lda_plus_U', 'lda_plus_u_kind', 'Hubbard_U', 'Hubbard_J', 'Hubbard_alpha', 'Hubbard_J0', 'Hubbard_beta', 'edir', 'emaxpos', 'eopreg', 'eamp', 'smearing', 'starting_ns_eigenvalue', 'U_projection_type', 'input_dft', 'la2F', 'assume_isolated', 'nqx1', 'nqx2', 'nqx3', 'ecutfock', 'exxdiv_treatment', 'x_gamma_extrapolation', 'yukawa', 'ecutvcut', 'exx_fraction', 'screening_parameter', 'ref_alat', 'noncolin', 'lspinorb', 'starting_spin_angle', 'lambda', 'angle1', 'angle2', 'report', 'lforcet', 'constrained_magnetization', 'B_field', 'fixed_magnetization', 'sic', 'sic_epsilon', 'force_pairing', 'sic_alpha', 'tot_charge', 'tot_magnetization', 'spline_ps', 'one_atom_occupations', 'vdw_corr', 'london', 'london_s6', 'london_rcut', 'london_c6', 'london_rvdw', 'ts_vdw', 'ts_vdw_isolated', 'ts_vdw_econv_thr', 'xdm', 'xdm_a1', 'xdm_a2', 'step_pen', 'A_pen', 'sigma_pen', 'alpha_pen', 'no_t_rev', 'esm_bc', 'esm_efield', 'esm_w', 'esm_nfit', 'esm_debug', 'esm_debug_gpmax', 'esm_a', 'esm_zb', 'fcp_mu', 'fcp_mass', 'fcp_tempw', 'fcp_relax_step', 'fcp_relax_crit', 'space_group', 'uniqueb', 'origin_choice', 'rhombohedral', 'zmon', 'relaxz', 'block', 'block_1', 'block_2', 'block_height')
NAMELIST['system'] += ('gau_parameter',) # append
 
NAMELIST['electrons'] = ('emass', 'emass_cutoff', 'orthogonalization', 'electron_maxstep', 'scf_must_converge', 'ortho_eps', 'ortho_max', 'electron_dynamics', 'electron_damping', 'electron_velocities', 'electron_temperature', 'ekincw', 'fnosee', 'ampre', 'grease', 'diis_size', 'diis_nreset', 'diis_hcut', 'diis_wthr', 'diis_delt', 'diis_maxstep', 'diis_rot', 'diis_fthr', 'diis_temp', 'diis_achmix', 'diis_g0chmix', 'diis_g1chmix', 'diis_nchmix', 'diis_nrot', 'diis_rothr', 'diis_ethr', 'diis_chguess', 'mixing_mode', 'mixing_beta', 'mixing_ndim', 'mixing_fixed_ns', 'tqr', 'tq_smoothing', 'tbeta_smoothing', 'diago_cg_maxiter', 'diago_david_ndim', 'diagonalization', 'startingpot', 'startingwfc', 'conv_thr', 'adaptive_thr', 'conv_thr_init', 'conv_thr_multi', 'diago_thr_init', 'n_inner', 'fermi_energy', 'rotmass', 'occmass', 'rotation_damping', 'occupation_damping', 'rotation_dynamics', 'occupation_dynamics', 'tcg', 'maxiter', 'etresh', 'passop', 'epol', 'efield', 'epol2', 'efield2', 'diago_full_acc', 'occupation_constraints', 'niter_cg_restart', 'niter_cold_restart', 'lambda_cold', 'efield_cart', 'real_space', 'tcpbo', 'emass_emin', 'emass_cutoff_emin', 'electron_damping_emin', 'dt_emin', 'efield_phase')
NAMELIST['electrons'] += ('tgrand','ortho_para',) # append or obsolete


NAMELIST['ions'] = ('ion_dynamics', 'iesr', 'ion_radius', 'ion_damping', 'ion_positions', 'ion_velocities', 'ion_temperature', 'tempw', 'fnosep', 'nhgrp', 'fnhscl', 'nhpcl', 'nhptyp', 'ndega', 'tranp', 'amprp', 'greasp', 'tolp', 'ion_nstepe', 'ion_maxstep', 'refold_pos', 'upscale', 'delta_t', 'pot_extrapolation', 'wfc_extrapolation', 'nraise', 'remove_rigid_rot', 'trust_radius_max', 'trust_radius_min', 'trust_radius_ini', 'w_1', 'w_2', 'bfgs_ndim', 'l_mplathe', 'n_muller', 'np_muller', 'l_exit_muller')

NAMELIST['cell'] = ('cell_parameters', 'cell_dynamics', 'cell_velocities', 'press', 'wmass', 'cell_temperature', 'temph', 'fnoseh', 'cell_dofree', 'greash', 'cell_factor', 'cell_nstepe', 'cell_damping', 'press_conv_thr')

'''
head -n 1233 input_parameters.f90 | awk /REAL/'{print $0}'
head -n 1233 input_parameters.f90 | awk -F"[:=]" /REAL/'{print $3}' | awk -F'(' '{print "'\''"$1"'\'',"}' | sed 's/ //g'
missing: 'qcutz','q2sigma','london_rcut', 'london_c6', 'london_rvdw'
'''                        
float_keys = (             
    'london_rcut', 
    'london_c6', 
    'london_rvdw',
    'dt',
    'refg',
    'max_seconds',
    'ekin_conv_thr',
    'etot_conv_thr',
    'forc_conv_thr',
    'celldm',
    'a',
    'c',
    'b',
    'cosab',
    'cosac',
    'cosbc',
    'ref_alat',
    'tot_charge',
    'tot_magnetization',
    'ecutwfc',
    'ecutrho',
    'degauss',
    'ecfixed',
    'starting_magnetization',
    'starting_ns_eigenvalue',
    'Hubbard_U',
    'Hubbard_J0',
    'Hubbard_J',
    'Hubbard_alpha',
    'Hubbard_beta',
    'A_pen',
    'sigma_pen',
    'alpha_pen',
    'exx_fraction',
    'screening_parameter',
    'gau_parameter',
    'yukawa',
    'ecutvcut',
    'conv_thr_init',
    'conv_thr_multi',
    'ecutfock',
    'emaxpos',
    'eopreg',
    'eamp',
    'zmon',
    'block_1',
    'block_2',
    'block_height',
    'lambda',
    'fixed_magnetization',
    'angle1',
    'angle2',
    'B_field',
    'sic_epsilon',
    'sic_alpha',
    'london_s6',
    'ts_vdw_econv_thr',
    'xdm_a1',
    'xdm_a2',
    'esm_efield',
    'esm_w',
    'esm_a',
    'esm_zb',
    'fcp_mu',
    'fcp_mass',
    'fcp_tempw',
    'fcp_relax_step',
    'fcp_relax_crit',
    'emass',
    'emass_cutoff',
    'ortho_eps',
    'electron_damping',
    'ekincw',
    'fnosee',
    'ampre',
    'grease',
    'diis_hcut',
    'diis_wthr',
    'diis_delt',
    'diis_fthr',
    'diis_temp',
    'diis_achmix',
    'diis_g0chmix',
    'diis_g1chmix',
    'diis_rothr',
    'diis_ethr',
    'mixing_beta',
    'diago_thr_init',
    'conv_thr',
    'lambda_cold',
    'fermi_energy',
    'rotmass',
    'occmass',
    'occupation_damping',
    'rotation_damping',
    'etresh',
    'passop',
    'efield',
    'efield_cart',
    'efield2',
    'emass_emin',
    'emass_cutoff_emin',
    'electron_damping_emin',
    'dt_emin',
    'ion_radius',
    'ion_damping',
    'tempw',
    'fnosep',
    'tolp',
    'fnhscl',
    'amprp',
    'greasp',
    'upscale',
    'delta_t',
    'trust_radius_max',
    'trust_radius_min',
    'trust_radius_ini',
    'w_1',
    'w_2',
    'press',
    'wmass',
    'temph',
    'fnoseh',
    'greash',
    'cell_factor',
    'cell_damping',
    'press_conv_thr',
    'qcutz',
    'q2sigma',
)

'''
head -n 1233 input_parameters.f90 | awk /INTEGER/'{print $0}'
head -n 1233 input_parameters.f90 | awk -F"[:=]" /INTEGER/'{print $3}' | awk -F'(' '{print "'\''"$1"'\'',"}' | sed 's/ //g'
missing: 'ortho_para','nqx2','nqx3',
'''
int_keys = (
    'ortho_para',
    'nqx2',
    'nqx3',
    'nstep',
    'iprint',
    'isave',
    'ndr',
    'ndw',
    'gdir',
    'nppstr',
    'nberrycyc',
    'ibrav',
    'nat',
    'ntyp',
    'nbnd',
    'nr1',
    'nr2',
    'nr3',
    'nr1s',
    'nr2s',
    'nr3s',
    'nr1b',
    'nr2b',
    'nr3b',
    'nspin',
    'lda_plus_u_kind',
    'nqx1',
    'edir',
    'report',
    'esm_nfit',
    'esm_debug_gpmax',
    'space_group',
    'origin_choice',
    'ortho_max',
    'electron_maxstep',
    'diis_size',
    'diis_nreset',
    'diis_maxstep',
    'diis_nchmix',
    'diis_nrot',
    'mixing_ndim',
    'diago_cg_maxiter',
    'diago_david_ndim',
    'mixing_fixed_ns',
    'n_inner',
    'niter_cold_restart',
    'maxiter',
    'niter_cg_restart',
    'epol',
    'epol2',
    'iesr',
    'nhpcl',
    'nhptyp',
    'nhgrp',
    'ndega',
    'ion_nstepe',
    'ion_maxstep',
    'nraise',
    'bfgs_ndim',
    'n_muller',
    'np_muller',
    'cell_nstepe',
)


'''
head -n 1233 input_parameters.f90 | awk /LOGICAL/'{print $0}'
head -n 1233 input_parameters.f90 | awk -F"[:=]" /LOGICAL/'{print $3}' | awk -F'(' '{print "'\''"$1"'\'',"}' | sed 's/ //g'
missing: noinv
'''
bool_keys = ( 
    'noinv',
    'tstress',
    'tprnfor',
    'tefield',
    'monopole',
    'tefield2',
    'lelfield',
    'lorbm',
    'dipfield',
    'lberry',
    'wf_collect',
    'saverho',
    'tabps',
    'lkpoint_dir',
    'use_wannier',
    'lecrpa',
    'tqmmm',
    'lfcpopt',
    'lfcpdyn',
    'nosym',
    'nosym_evc',
    'force_symmorphic',
    'use_all_frac',
    'lda_plus_U',
    'la2F',
    'step_pen',
    'x_gamma_extrapolation',
    'adaptive_thr',
    'relaxz',
    'block',
    'noncolin',
    'lspinorb',
    'lforcet',
    'starting_spin_angle',
    'no_t_rev',
    'force_pairing',
    'spline_ps',
    'one_atom_occupations',
    'london',
    'ts_vdw',
    'ts_vdw_isolated',
    'xdm',
    'esm_debug',
    'uniqueb',
    'rhombohedral',
    'scf_must_converge',
    'diis_rot',
    'diis_chguess',
    'diago_full_acc',
    'tgrand',
    'tcg',
    'real_space',
    'tqr',
    'tq_smoothing',
    'tbeta_smoothing',
    'occupation_constraints',
    'tcpbo',
    'tranp',
    'refold_pos',
    'remove_rigid_rot',
    'l_mplathe',
    'l_exit_muller',
)

'''
head -n 1233 input_parameters.f90 | awk /LOGICAL/'{print $0}'
head -n 1233 input_parameters.f90 | awk -F"[:=]" /CHARACTER/'{print $4}' | awk -F'(' '{print "'\''"$1"'\'',"}' | sed 's/ //g'
missing: 'wfc_extrapolation'
redundant: 'calculation_allowed', 'verbosity_allowed', 'restart_mode_allowed', 'exxdiv_treatment_allowed', 'electron_dynamics_allowed',
    'ion_dynamics_allowed','cell_dynamics_allowed','memory_allowed',
'''

char_keys = (
    'wfc_extrapolation',
    'title',
    'calculation',
    'verbosity',
    'restart_mode',
    'outdir',
    'prefix',
    'pseudo_dir',
    'wfcdir',
    'disk_io',
    'vdw_table_name',
    'point_label_type',
    'memory',
    'input_xml_schema_file',
    'occupations',
    'smearing',
    'input_dft',
    'U_projection_type',
    'exxdiv_treatment',
    'constrained_magnetization',
    'sic',
    'assume_isolated',
    'vdw_corr',
    'esm_bc',
    'orthogonalization',
    'electron_dynamics',
    'electron_velocities',
    'electron_temperature',
    'startingwfc',
    'mixing_mode',
    'diagonalization',
    'startingpot',
    'rotation_dynamics',
    'occupation_dynamics',
    'efield_phase',
    'ion_dynamics',
    'ion_positions',
    'ion_velocities',
    'ion_temperature',
    'pot_extrapolation',
    'cell_parameters',
    'cell_dynamics',
    'cell_velocities',
    'cell_temperature',
    'cell_dofree',
)
